name: Contents Status

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  check_contents:
    name: ContentsTableCheck
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: check contents table
      run: |
        go build -o postctl ./cmd/postctl/main.go
        ./postctl contents -p "https://github.com/po3rin/post/tree/master" -l
